// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gamdcbocntujlomnutcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhbWRjYm9jbnR1amxvbW51dGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MDg3ODIsImV4cCI6MjA1MzA4NDc4Mn0.69R9zsIBdPbupShn7LmW4zC97ZXkC2QZ04Mw11Qh2RM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);